name: multiview-cbm
channels:
  - pytorch
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - cudatoolkit=10.2.89
  - cycler=0.11.0
  - dbus=1.13.18
  - et_xmlfile=1.1.0
  - expat=2.4.4
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openpyxl=3.0.9
  - openssl=1.1.1q
  - packaging=21.3
  - pcre=8.45
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.27.1
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - tqdm=4.64.0
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.8
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - alembic==1.7.7
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - brotlipy==0.7.0
    - certifi==2022.9.24
    - cffi==1.15.0
    - click==8.1.3
    - cloudpickle==2.0.0
    - cryptography==36.0.0
    - databricks-cli==0.16.6
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker==5.0.3
    - docopt==0.6.2
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - flask==2.1.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - greenlet==1.1.2
    - gunicorn==20.1.0
    - imgcrop==0.1.0
    - importlib-metadata==4.11.3
    - ipykernel==6.13.0
    - ipython==8.2.0
    - ipython-genutils==0.2.0
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.2.2
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - kiwisolver==1.3.1
    - mako==1.2.0
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - nbclient==0.6.0
    - nbconvert==6.5.0
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - notebook==6.4.11
    - numpy==1.21.5
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - pip==21.2.4
    - progressbar2==4.0.0
    - prometheus-client==0.14.1
    - prometheus-flask-exporter==0.20.1
    - prompt-toolkit==3.0.29
    - protobuf==3.20.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.11.2
    - pyjwt==2.3.0
    - pykwalify==1.8.0
    - pyradiomics==3.0.1
    - pyrsistent==0.18.1
    - pysocks==1.7.1
    - python-utils==3.1.0
    - pytz==2022.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - querystring-parser==1.2.4
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - send2trash==1.8.0
    - setuptools==61.2.0
    - simpleitk==2.2.0
    - sip==4.19.13
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.36
    - sqlparse==0.4.2
    - stack-data==0.2.0
    - tabulate==0.8.9
    - terminado==0.13.3
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - torch==1.11.0
    - torchaudio==0.11.0
    - torchvision==0.12.0
    - tornado==6.1
    - traitlets==5.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.2
    - werkzeug==2.1.2
    - zipp==3.8.0
