# An example configuration file for training an SSMVCBM on the MVAwA data

# --------------------------
#         Experiment
# --------------------------
experiment_name: 'ssmvcbm-mvawa'
run_name: 'test-42'
seed: 42
validate: False
k_folds: 5
device: 'cuda'
workers: 2
# TODO: specify relevant directories below
log_directory: '...'
model_directory: '...'

# --------------------------
#         Dataset
# --------------------------
dataset: 'mawa'
num_views: 4
num_classes: 50
partial_concepts: False
preload: False

# --------------------------
#         Model
# --------------------------
model: 'SSMVCBM'
encoder_arch: 'ResNet18'
aggregator: 'mean'
num_s_concepts: 85
num_us_concepts: 25
t_hidden_dim: 100
norm_bottleneck: False
usc_out_activation: 'tanh'
attention: False
usc_attention: False

# --------------------------
#         Training
# --------------------------
sc_epochs: 25
sc_learning_rate: 0.0001

adversarial_it: 7
adversary: True
beta: 0.01

usc_gamma: 0

d_epochs: 10
d_learning_rate: 0.01

usc_epochs: 15
usc_learning_rate: 0.0001

t_epochs: 20
t_learning_rate: 0.01

train_batch_size: 64
val_batch_size: 64

optimizer: 'adam'

decrease_every: 150
lr_divisor: 2

weight_decay: 0

validate_every_epoch: False

# --------------------------
#     Additional features
# --------------------------
ex_features: []
