# An example configuration file for training an MVCBM on the pediatric appendicitis data

# --------------------------
#         Experiment
# --------------------------
experiment_name: 'mvcbm-app'
run_name: 'test-42'
seed: 42
validate: False
k_folds: 5
device: 'cuda'
workers: 2
# TODO: specify relevant directories below
log_directory: '...'
model_directory: '...'

# --------------------------
#         Dataset
# --------------------------
dataset: 'app'
num_classes: 2
# TODO: specify relevant directories below
images: '...'
test_images: '...'
dict_file: '...'
dict_file_test: '...'
preload: False

# --------------------------
#         Augmentation
# --------------------------
augmentation: True
aug_per_sample: 1
hist_equal: True
normalize: False
brightness: True
rotate: True
shear: True
resize: True
gamma: True
sharpness: True
gaussian_noise: True
poisson_noise: False
SP_noise: False
zero_rect: 0.05

# --------------------------
#         Model
# --------------------------
model: 'MVCBM'
encoder_arch: 'ResNet18'
aggregator: 'lstm'
training_mode: 'sequential'
alpha: 1.0
num_concepts: 9
t_hidden_dim: 5
norm_bottleneck: False
attention: False

# --------------------------
#         Training
# --------------------------
c_epochs: 20
c_learning_rate: 0.0001

t_epochs: 20
t_learning_rate: 0.01

j_epochs: 40
j_learning_rate: 0.001

train_batch_size: 4
val_batch_size: 4

optimizer: 'adam'

decrease_every: 150
lr_divisor: 2

weight_decay: 0

validate_every_epoch: False

# --------------------------
#     Additional features
# --------------------------
ex_features: []
